### ISSUE TITLE
"voda" integrator, derivative error

### ISSUE THREAD

**Issue by baba-mpe** [neurophysik/jitcode#7]
Hi there,

I'm currently implementing an MCMC method for Bayesian inference based on a rather stiff ODE model, which describes cardiac excitation. Since I'll be running the forward solve for this model many times, I resorted to using jitcode instead of the standard scipy solve. Potentially due to stiffness, the explicit integrators from jitcode don't give me the right answers (see attached script comparing with scipy implicit solve). Unfortunately, using the implicit method "voda" produces the error below. This could be due to a heavyside function in the formulation of the time derivative, which complicates symbolic differentiation? Is there any way to resolve this problem using "voda" without explicitly changing the ODE?
[cardiacExcitation.txt](https://github.com/neurophysik/jitcode/files/2512232/cardiacExcitation.txt)

Generating, compiling, and loading C code.
generated C code for f
generated symbolic Jacobian
/home/baba/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py:197: UserWarning: Traceback (most recent call last):
  File "/home/baba/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py", line 195, in _attempt_compilation
    self.compile_C()
  File "/home/baba/.local/lib/python3.6/site-packages/jitcode/_jitcode.py", line 400, in compile_C
    self._generate_jac_C()
  File "/home/baba/.local/lib/python3.6/site-packages/jitcode/_jitcode.py", line 260, in _generate_jac_C
    self.generate_jac_C()
  File "/home/baba/.local/lib/python3.6/site-packages/jitcode/_jitcode.py", line 329, in generate_jac_C
    arguments = arguments+[("dfdY", "PyArrayObject *__restrict const")]
  File "/home/baba/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py", line 189, in render_and_write_code
    omp
  File "/home/baba/.local/lib/python3.6/site-packages/jitcxde_common/code.py", line 52, in write_in_chunks
    first_chunk.append(next(lines))
  File "/home/baba/.local/lib/python3.6/site-packages/jitcxde_common/code.py", line 9, in codelines
    for expression in expressions:
  File "/home/baba/.local/lib/python3.6/site-packages/jitcode/_jitcode.py", line 324, in <genexpr>
    for j,entry in enumerate(line)
  File "/home/baba/.local/lib/python3.6/site-packages/jitcode/_jitcode.py", line 284, in <genexpr>
    jac_sym_wc = ( (entry.subs(self.general_subs) for entry in line) for line in self.jac_sym )
  File "/home/baba/.local/lib/python3.6/site-packages/jitcode/_jitcode.py", line 41, in line
    entry = f_entry.diff(y(j))
  File "symengine_wrapper.pyx", line 878, in symengine.lib.symengine_wrapper.Basic.diff
RuntimeError: Derivative doesn't exist.

  warn(format_exc())
/home/baba/.local/lib/python3.6/site-packages/jitcxde_common/_jitcxde.py:199: UserWarning: 
============================================================
READ ME FIRST
============================================================
Generating compiled integrator failed; resorting to lambdified functions. If you can live with using the Python backend, you can call generate_lambdas to explicitly do this and bypass the compile attempt and error messages. Otherwise, you want to take care of fixing the above errors.
============================================================

============================================================

  warn(line + "READ ME FIRST" + line + "Generating compiled integrator failed; resorting to lambdified functions. If you can live with using the Python backend, you can call generate_lambdas to explicitly do this and bypass the compile attempt and error messages. Otherwise, you want to take care of fixing the above errors." + 2*line)
generated lambdified f

....
RuntimeError: Derivative doesn't exist.

**Comment by Wrzlprmft** [comment]
I haven’t looked deeply into this, but yes, the Heaviside functions are at least one big source of trouble for two reasons:

* Many (if not all) Integrators require continuity of the derivative. It is therefore almost always better to replace your Heaviside function with a sharp sigmoidal. (It’s also very likely more realistic.) This is also addressed in in the second point [here](https://jitcde-common.readthedocs.io/en/stable/#common-mistakes-and-questions). Note that even your perceived stiffness of the problem may be due to this.

* You do not even get there, due to the following lines in your code:

	```Python
	def dydtJitcode(y,Gna,g21,g22):
	[…]
	U = y(0)
	[…]
	if U < Edag:
		G = k1*(E1-U);
	elif (U>=Edag) and (U < Estar):
		G = k2*(U-E2)
	elif (U >= Estar):
		G = k3*(E3-U)
	```

	Here `U` is a symbol representing one of your states. You run comparisons with it when *defining* your derivative, not when *evaluating* it. Your `dydtJitcode` is called exactly once before JiTCODE even enters the arena, and the entire point of JiTCODE is that it does not call Python functions during integration time. Even worse, what happens is that `U < Edag` creates a symbolic comparison object. This object is truthy and thus the first `if` statement is True when you call the function. The code never reaches either `elif`. To better understand this, looking at the following short script may help:

	```Python
	from sympy.abc import x
	print(x>0)
	if x>0:
		print("blobfish")
	```
