### ISSUE TITLE
pickle error with multiprocessing

### ISSUE THREAD

**Issue by baba-mpe** [neurophysik/jitcode#8]
Hi there,

within a Monte Carlo method I've been writing, generating a single new sample requires solving an underlying ODE, thus I'm solving the ODE many times, each time with a different input. Using Jitcode instead of Scipy speeded up things significantly. However, I'd like to go a step further and run different solves - since they are independent from each other - in parallel. In order to do that I'm passing arguments in terms of a lambda function and give that lambda function to pool.map. Now the standard multiprocessing library doesn't like that, and gives a pickle error. Therefore, I'm using pathos.multiprocessing, which then works if the computation is done in __main__. However, what I really need is to run the multiprocessing computation within a method of a class. What happens then is that I receive the following pickle error stated below. The same thing works however when using multiprocessing with Scipy. A small working example is attached. Do you have any suggestion how to resolve this?
[multi_pickleError.txt](https://github.com/neurophysik/jitcode/files/2519770/multi_pickleError.txt)

Traceback (most recent call last):

  File "<ipython-input-5-5f8ecc6969c7>", line 1, in <module>
    runfile('/home/baba/PhD/simulations/MP-Quasi-MCMC/CardiacExcitation/Model/test3.py', wdir='/home/baba/PhD/simulations/MP-Quasi-MCMC/CardiacExcitation/Model')

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/baba/PhD/simulations/MP-Quasi-MCMC/CardiacExcitation/Model/test3.py", line 138, in <module>
    A = multiSolver(N)

  File "/home/baba/PhD/simulations/MP-Quasi-MCMC/CardiacExcitation/Model/test3.py", line 101, in multiSolver
    xy_t =  pool.map(lambdaFun, ForwardProposals)

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/multiprocess/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/multiprocess/pool.py", line 644, in get
    raise self._value

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/multiprocess/pool.py", line 424, in _handle_tasks
    put(task)

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol).dump(obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 409, in dump
    self.save(obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 1377, in save_function
    obj.__dict__), obj=obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 1120, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 634, in save_reduce
    save(state)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 847, in _batch_setitems
    save(v)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 1377, in save_function
    obj.__dict__), obj=obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 1120, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 781, in save_list
    self._batch_appends(obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 805, in _batch_appends
    save(x)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 751, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 610, in save_reduce
    save(args)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 736, in save_tuple
    save(element)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 609, in save_reduce
    save(func)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self

  File "/home/baba/Progs/anaconda3/lib/python3.6/site-packages/dill/_dill.py", line 1321, in save_type
    StockPickler.save_global(pickler, obj)

  File "/home/baba/Progs/anaconda3/lib/python3.6/pickle.py", line 927, in save_global
    (obj, module_name, name))

PicklingError: Can't pickle y: it's not the same object as __main__.y

**Comment by Wrzlprmft** [comment]
At a quick glance: Use [`save_compiled`](https://jitcode.readthedocs.io/#_jitcode.jitcode.save_compiled) instead of pickling. (I will have a more thorough look later.)

**Comment by Wrzlprmft** [comment]
After a more thorough look:

* JiTCODE does not support pickle right now.

* Having JiTCODE support pickling (or something similar) would be a nightmare, if not impossible due to the just-in-time-compiled components. Given that `save_compiled` is as well for all situations where I can conceive that pickling is used, it is not likely to happen.

* If you want to use something compiled on another machine – be it via `save_compiled` or pickling –, it has to work with that machine’s architecture and libraries.

**Comment by Wrzlprmft** [comment]
Thanks to your input, [future users will now receive a more helpful error message when trying to pickle JiTC*DE objects](https://github.com/neurophysik/jitcxde_common/commit/d79d3e054df835f1ed6d3976420ab165245ce8eb).

**Comment by baba-mpe** [comment]
Okay, thanks. However, I'm not sure what the use of save_compiled functionality would entail in terms building a pool of processes... attempts of debugging this failed. Any further hint?

**Comment by Wrzlprmft** [comment]
I am not exactly sure how your pooling tool works, but the intended workflow would be:

1. Compile your right-hand side *(f)* once and save it using `save_compiled`.
2. Provide the resulting file to every instance of the pooled process.
3. In each pooled process, initialise `jitcode` directly with the compiled file by using the `module_location` argument. This way you do not have to recompile.
